name: Plex Media Server
description: |
  Plex organizes video, music and photos from personal media libraries and streams them to smart TVs, streaming boxes and mobile devices. This container is packaged as a standalone Plex Media Server.
version: latest
category: Media
maintainer: LinuxServer.io
projectURL: https://plex.tv/
