plex:
  image: linuxserver/plex
  container_name: plex
  volumes:
    - /opt/appdata/plex:/config
    - /mnt/storage:/data
  net: host
  restart: always
  environment:
    - VERSION=plexpass
    - PUID=${PUID}
    - PGID=${PGID}
