plex:
  image: linuxserver/plex
  volumes:
    - ${path-config}:/config
    - ${path-data}:/data
  net: host
  restart: always
  environment:
    - VERSION=plexpass
    - PUID=${PUID}
    - PGID=${PGID}
